# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - jfding
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
